# Generated by Django 4.1.8 on 2023-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksteps',
            old_name='Steps',
            new_name='body',
        ),
    ]
