# Generated by Django 4.1.8 on 2023-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_steps_tasksteps_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpage',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('P', 'Planned'), ('D', 'Done')], default='Planned', max_length=1),
        ),
    ]
